<?php

/**
 * @file
 * Code for the [ESF] TC Library feature.
 */

include_once 'esf_tc_library.features.inc';

/**
 * Implements hook_file_download().
 *
 * Restricts access to private files in forum controlled by workbench.
 */
function esf_tc_library_file_download($uri) {
  global $user;
  workbench_access_user_load_data($user);
  $workbench_tids = array_keys($user->workbench_access);
  $query = db_select('file_usage', 'fu');
  $query->fields('fu', array('id', 'type'));
  $query->join('file_managed', 'fm', 'fm.fid = fu.fid');
  $query->condition('fm.uri', $uri, '=');
  $result = $query->execute();

  foreach ($result as $record) {

    /* If this file is used in a research node where Display File(s)
    is not checked, don't allow user to view file. */

    switch ($record->type) {
      case 'node':
        $node_wrapper = entity_metadata_wrapper('node', node_load($record->id));
        break;

      case 'comment':
        $comment = comment_load($record->id);
        $comment_nid = $comment->nid;
        $node_wrapper = entity_metadata_wrapper('node', node_load($comment_nid));
        break;
    }
    if (isset($node_wrapper->type) && $node_wrapper->type->value() == 'forum') {
      $forum_term = $node_wrapper->taxonomy_forums->raw();
      if (!in_array($forum_term, $workbench_tids)) {
        return -1;
      }
    }
  }
}

/**
 * Override common.js file for filedepot to display reports as collapsed.
 */
function esf_tc_library_js_alter(&$javascript) {
  $file_depot_path = drupal_get_path('module', 'filedepot') . '/js/common.js';
  $esf_tc_theme_path = drupal_get_path('theme', 'esf_tc') . '/scripts/common.js';
  $javascript[$file_depot_path]['data'] = $esf_tc_theme_path;
}
