<?php

/**
 * @file
 * Code for the esf_tc_content_types feature.
 */

include_once 'esf_tc_content_types.features.inc';
include_once 'esf_tc_content_types.theme.inc';
include_once 'esf_tc_content_types.block.inc';
include_once 'esf_tc_content_types.tokens.inc';
include_once 'esf_tc_content_types.notification.inc';
include_once 'esf_tc_content_types.tca.inc';
include_once 'esf_tc_content_types.whoswho.inc';

/**
 * Implements hook_permission().
 */
function esf_tc_content_types_permission() {
  // Block And Archive permission.
  $project_database_ct = _esf_tc_content_types_get_project_database_types();
  $perm = array();
  if (is_array($project_database_ct)) {
    foreach ($project_database_ct as $type) {
      $info = node_type_get_type($type);
      $perm += array(
        "archive any $type content" => array(
          'title' => t('%type_name: Archive any content', array('%type_name' => $info->name)),
        ),
        "block any $type content" => array(
          'title' => t('%type_name: Block any content', array('%type_name' => $info->name)),
        ),
        "republish any $type content" => array(
          'title' => t('%type_name: Publish any blocked, need deletion and archived content', array('%type_name' => $info->name)),
        ),
      );
    }
  }
  return $perm;
}

/**
 * Implements hook_node_presave().
 */
function esf_tc_content_types_node_presave($node) {
  global $user;

  if ($node->type == 'forum' && $node->is_new) {
    // Notify forum moderator on new content.
    $forum_term = taxonomy_term_load($node->taxonomy_forums[LANGUAGE_NONE][0]['tid']);
    $emails = _esf_tc_content_types_get_forum_moderators($forum_term);
    if (!empty($emails)) {
      rules_invoke_component('esf_tc_content_types_notify_forum_moderator_on_new_post', $user, $emails, $forum_term, $node);
    }
  }

  // Check if data have changed (Published only).
  $status = "";
  if ($node->type == 'esf_tnc_tca' && !$node->is_new) {
    $status = $node->field_esf_editorial_status[LANGUAGE_NONE][0]['value'];

    if ($status == 'published') {

      // Projects partners detect changes.
      $partners_data = $node->field_tca_partner_organisations[LANGUAGE_NONE];
      $partners_data_original = $node->original->field_tca_partner_organisations[LANGUAGE_NONE];

      $parnters_changed = FALSE;
      // Deletion detection.
      if (count($partners_data) != count($partners_data_original)) {
        $parnters_changed = TRUE;
      }
      elseif (!empty($partners_data)) {
        // Detect if a project partner is inserted.
        $count = count($partners_data);
        while ($count-- && !$parnters_changed) {
          if (!empty($partners_data[$count]['entity'])) {
            if (empty($partners_data[$count]['entity']->item_id)) {
              $parnters_changed = TRUE;
            }
          }
        }
      }
      // Change partners status if a change is detected.
      if ($parnters_changed || _esf_tc_content_types_sensitive_data_changed($node)) {
        foreach ($partners_data as &$partner) {
          $new_status = 'pending-key-changes';
          $partner['entity']->field_fc_mas_approval_status[LANGUAGE_NONE][0]['value'] = $new_status;
        }
        unset($partner);
        $node->field_tca_status[LANGUAGE_NONE][0]['value'] = 'orange';
        $node->field_esf_editorial_status[LANGUAGE_NONE][0]['value'] = 'draft';
        $node->status = 0;
      }
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function esf_tc_content_types_node_insert($node) {
  // Notidy project databases content types.
  _esf_tc_content_types_node_notify($node);
}

/**
 * Implements hook_node_update().
 */
function esf_tc_content_types_node_update($node) {
  // Notidy project databases content types.
  _esf_tc_content_types_node_notify($node);

  if (in_array($node->type, _esf_tc_content_types_get_project_database_types()) && $node->type != 'esf_tnc_call_for_project') {
    // Check if blocked.
    $wrapper = entity_metadata_wrapper('node', $node);
    $wrapper_original = entity_metadata_wrapper('node', $node->original);

    $tca_altered = FALSE;
    $node_blocked = FALSE;

    $ed_status = $wrapper->field_esf_editorial_status->value();
    if ($ed_status != $wrapper_original->field_esf_editorial_status->value() && $ed_status == 'blocked') {
      $node_blocked = TRUE;
    }
    else {
      $tca_altered = _esf_tc_content_types_sensitive_data_changed($node);
    }

    if ($tca_altered || $node_blocked) {
      $tca = _esf_tc_content_types_find_related_tca($node);
      if (!empty($tca)) {
        $tcas_title = array();
        foreach ($tca as $key => $t) {
          $tcas_title[] = $t->title . ' (TCA-' . $key . ')';
          $wrapper_tca = entity_metadata_wrapper('node', $t);
          // TCA status is changed to orange or red.
          $color_status = $node_blocked ? 'red' : 'orange';
          if ($wrapper_tca->field_tca_status->value() != 'red') {
            $wrapper_tca->field_tca_status = $color_status;
            $new_status = $node_blocked ? 'rejected' : 'pending-key-changes';
            foreach ($wrapper_tca->field_tca_partner_organisations->getIterator() as $partner) {
              $pjt = $partner->field_fc_partner_project->value();
              if (!empty($pjt) && ($node->type != 'esf_tnc_project' || $pjt->nid == $node->nid)) {
                $partner->field_fc_mas_approval_status = $new_status;
                $partner->save();
              }
            }
            unset($partner);
            $wrapper_tca->field_esf_editorial_status = 'draft';
            $wrapper_tca->status = 0;
            $wrapper_tca->save();
          }
        }
        unset($key, $t);
        if ($node_blocked) {
          watchdog('TCA regression', '%title has been blocked. Following tca have been impacted : %tcas', array(
            '%title' => $node->title,
            '%tcas' => drupal_implode_tags($tcas_title),
          ));
        }
        elseif ($tca_altered) {
          watchdog('TCA regression', 'Sensitive data changes detected on %title. Following tca have been impacted : %tcas', array(
            '%title' => $node->title,
            '%tcas' => drupal_implode_tags($tcas_title),
          ));
        }
      }
    }
  }
}

/**
 * Implements hook_field_collection_item_insert().
 */
function esf_tc_content_types_field_collection_item_insert(FieldCollectionItemEntity $field_collection_item) {
  // Notidy project databases contact field collection.
  _esf_tc_content_types_field_collection_notify($field_collection_item);
}

/**
 * Implements hook_field_collection_item_update().
 */
function esf_tc_content_types_field_collection_item_update(FieldCollectionItemEntity $field_collection_item) {
  // Notidy project databases contact field collection.
  _esf_tc_content_types_field_collection_notify($field_collection_item);
}

/**
 * Implements hook_comment_insert().
 */
function esf_tc_content_types_comment_insert($comment) {
  global $user;

  // Notify forum moderator on new comment.
  $node = node_load($comment->nid);
  $forum_term = taxonomy_term_load($node->taxonomy_forums[LANGUAGE_NONE][0]['tid']);
  $emails = _esf_tc_content_types_get_forum_moderators($forum_term);
  if (!empty($emails)) {
    rules_invoke_component('esf_tc_content_types_notify_forum_moderator_on_new_comment', $user, $emails, $forum_term, $node, $comment);
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter contact profile form.
 */
function esf_tc_content_types_form_profile2_edit_contact_profile_form_alter(&$form, &$form_state) {
  $form['actions']['submit']['#submit'][] = '_esf_tc_content_types_contact_submit';
  $form['profile_contact_profile']['field_editorial_status']['#access'] = FALSE;
}

/**
 * Custom submit for the contact profile form.
 */
function _esf_tc_content_types_contact_submit($form, &$form_state) {
  $contact_uid = $form_state['user']->uid;
  // Synchronize the user with all organisation using the token email.
  $token_email = $form_state['values']['profile_contact_profile']['field_token_email'][LANGUAGE_NONE][0]['email'];
  if (!empty($token_email)) {
    // Get all organisations having this email as legal contact and
    // set unknown contact.
    $query = db_select('node', 'n')
      ->fields('n', array('nid'));
    $query->join('field_data_field_org_contact_legal_email', 'e', 'n.nid = e.entity_id');
    $query->join('field_data_field_esf_country_ref', 'c', 'n.nid = c.entity_id');
    $query->condition('e.field_org_contact_legal_email_value', $token_email);
    $result = $query->execute();

    foreach ($result as $org) {
      $contact = node_load($org->nid);
      $contact_wrapper = entity_metadata_wrapper('node', $contact);
      // Save info about current contact.
      $contact_wrapper->field_org_contact_account->set('yes');
      $contact_wrapper->field_org_contact->set($contact_uid);
      // Reset previous contact value.
      $contact_wrapper->field_org_contact_legal_name->set('');
      $contact_wrapper->field_org_contact_legal_email->set('');
      $contact_wrapper->save();
    }

    // Get all field collections having this email as legal contact and
    // set as unknown contact.
    $query = db_select('field_data_field_fc_org_email', 'e')
      ->fields('e', array('entity_id'));
    $query->condition('e.field_fc_org_email_value', $token_email);
    $result = $query->execute();

    foreach ($result as $coll) {
      // Load field collection.
      $contact = field_collection_item_load($coll->entity_id);
      $contact_wrapper = entity_metadata_wrapper('field_collection_item', $contact);
      // Save info about current contact.
      $contact_wrapper->field_fc_contact_account->set('yes');
      $contact_wrapper->field_fc_org_contact->set($contact_uid);
      // Reset previous contact value.
      $contact_wrapper->field_fc_org_name->set('');
      $contact_wrapper->field_fc_org_email->set('');
      $contact_wrapper->save();
    }

    // Reset token value.
    $form_state['values']['profile_contact_profile']['field_token_email'][LANGUAGE_NONE][0]['email'] = '';

    drupal_set_message(t('Your account has been synchronized with all organisations that were referencing you.'));
  }
  profile2_form_submit_handler($form, $form_state);
  $form_state['redirect'] = 'user/' . $contact_uid;
}

/**
 * Implements hook_form_alter().
 */
function esf_tc_content_types_form_alter(&$form, &$form_state, $form_id) {
  // Transform editorial status to buttons.
  $editorial_field_name = _esf_tc_content_types_get_editorial_status_field_name();
  $color_class = array(
    'success' => 'btn-success',
    'info' => 'btn-info',
    'warning' => 'btn-warning',
    'danger' => 'btn-danger',
    'primary' => 'btn-primary',
  );

  // Avoid checking on ajax refresh.
  if (isset($form[$editorial_field_name])) {
    // Add Submit method.
    $form['#submit'][] = 'esf_tc_content_types_projects_database_submit';
    // Hide Select list.
    $form[$editorial_field_name]['#access'] = FALSE;
    // Create alternative buttons.
    $state = reset($form[$editorial_field_name][LANGUAGE_NONE]['#default_value']);
    $weight = $form['actions']['submit']['#weight'] + 1;

    // Alert if status is not published.
    if (!isset($form_state['input']['ajax_html_ids'])) {
      _esf_tc_content_type_display_message($form['#node'], $state);
      $_arr_types = array(
        'esf_tnc_project',
        'esf_tnc_call_for_project',
        'esf_tnc_tca',
      );
      if (!isset($form['#node']->nid) && in_array($form['#node']->type, $_arr_types)) {
        _esf_tc_content_types_advice_message($form['#node']->type);
      }
    }

    $form['actions']['submit']['#access'] = _esf_tc_content_types_button_access('submit', $form['type']['#value'], $form['#node'], $state);

    if ($state == 'draft') {
      // Save as draft button.
      $form['actions']['submit']['#value'] = t('Save as draft');
    }

    if ($form['#node']->type == 'esf_tnc_tca' && in_array($state, array('draft'))) {
      // Submit to the MA/IBS button for TCA.
      $form['actions']['negotiation'] = $form['actions']['submit'];
      $form['actions']['negotiation']['#value'] = t('Submit to IB/MA for validation');
      $form['actions']['negotiation']['#weight'] = $weight++;
      $form['actions']['negotiation']['#attributes']['class'][] = $color_class['primary'];
      $form['actions']['negotiation']['#access'] = _esf_tc_content_types_button_access('negotiation', $form['type']['#value'], $form['#node'], $state);
    }
    elseif ($state != 'published') {
      // Publish button.
      $form['actions']['published'] = $form['actions']['submit'];
      $form['actions']['published']['#value'] = t('Publish');
      $form['actions']['published']['#weight'] = $weight++;
      $form['actions']['published']['#attributes']['class'][] = $color_class['success'];
      $form['actions']['published']['#access'] = _esf_tc_content_types_button_access('publish', $form['type']['#value'], $form['#node'], $state);
    }

    // If node exists.
    if ($form['nid']['#value']) {
      // Block button.
      $form['actions']['block'] = $form['actions']['submit'];
      $form['actions']['block']['#value'] = t('Block');
      $form['actions']['block']['#weight'] = $weight++;
      $form['actions']['block']['#attributes']['class'][] = $color_class['warning'];
      $form['actions']['block']['#access'] = _esf_tc_content_types_button_access('block', $form['type']['#value'], $form['#node'], $state);
      // Archive button.
      $form['actions']['archive'] = $form['actions']['submit'];
      $form['actions']['archive']['#value'] = t('Archive');
      $form['actions']['archive']['#weight'] = $weight++;
      $form['actions']['archive']['#attributes']['class'][] = $color_class['warning'];
      $form['actions']['archive']['#access'] = _esf_tc_content_types_button_access('archive', $form['type']['#value'], $form['#node'], $state);
      // Ask for deletion button.
      $form['actions']['ask_deletion'] = $form['actions']['submit'];
      $form['actions']['ask_deletion']['#value'] = t('Ask for deletion');
      $form['actions']['ask_deletion']['#weight'] = $weight++;
      $form['actions']['ask_deletion']['#attributes']['class'][] = $color_class['danger'];
      $form['actions']['ask_deletion']['#access'] = _esf_tc_content_types_button_access('needs-deletion', $form['type']['#value'], $form['#node'], $state);
    }
    // Delete.
    if (isset($form['actions']['delete']) && $form['actions']['delete']) {
      $form['actions']['delete']['#attributes']['class'][] = $color_class['danger'];
    }
  }

  // Hide format text option under text editor.
  drupal_add_js('jQuery(window).load(function() {jQuery(".filter-wrapper").hide();});', 'inline');
  // Hide Show row weights link.
  drupal_add_js('jQuery(window).load(function() {jQuery(".tabledrag-toggle-weight").hide();});', 'inline');
  drupal_add_js('jQuery(document).ajaxSuccess(function() {jQuery(".tabledrag-toggle-weight").hide();});', 'inline');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter organisation node form.
 */
function esf_tc_content_types_form_esf_tnc_organisation_node_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  // Add afterbuild function to manage states on field collection.
  $form['field_org_additional_contacts'][LANGUAGE_NONE]['#after_build'][] = 'esf_tc_content_types_field_org_additional_contacts_after_build';

  // Add custom validate function.
  $form['#validate'][] = 'esf_tc_content_types_projects_database_draft_validate';
  $form['#validate'][] = 'esf_tc_content_types_organisation_validate';

  // Hide body field.
  $form['body']['#access'] = FALSE;

  // Hide MA For users which are not webmaster.
  if (!in_array('webmaster', $user->roles) && !in_array('administrator', $user->roles)) {
    unset($form['field_org_is_ma_ib']);
    $form['field_org_is_ma_ib'] = array(
      '#type' => 'value',
      '#value' => 0,
    );
  }

  // Other countries field states.
  $other_country_term_tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'esf_countries_regions');
  if ($other_country_term_tid != NULL) {
    $form['field_org_other_countries']['#states'] = array(
      'visible' => array(
        ':input[name="field_esf_country_ref[und]"]' => array('value' => $other_country_term_tid),
      ),
      'required' => array(
        ':input[name="field_esf_country_ref[und]"]' => array('value' => $other_country_term_tid),
      ),
    );
  }

  // Other type of organisation field states.
  $other_organisation_term_tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'organisation_types');
  if ($other_organisation_term_tid != NULL) {
    $form['field_org_specify_type']['#states'] = array(
      'visible' => array(
        ':input[name="field_org_type_of_organisation[und]"]' => array('value' => $other_organisation_term_tid),
      ),
      'required' => array(
        ':input[name="field_org_type_of_organisation[und]"]' => array('value' => $other_organisation_term_tid),
      ),
    );
  }

  // Legal contact fields states.
  $form['field_org_contact_legal_name']['#states'] = array(
    'visible' => array(
      ':input[name="field_org_contact_account[und]"]' => array('value' => 'no'),
    ),
  );

  $form['field_org_contact_legal_email']['#states'] = array(
    'visible' => array(
      ':input[name="field_org_contact_account[und]"]' => array('value' => 'no'),
    ),
  );

  $form['field_org_contact']['#states'] = array(
    'visible' => array(
      ':input[name="field_org_contact_account[und]"]' => array('value' => 'yes'),
    ),
  );

  // Notification system.
  $form['field_org_notif_address']['#states'] = array(
    'disabled' => array(
      ':input[name="field_org_notif_choice[und]"]' => array('value' => 0),
    ),
  );

  // Change Field Access.
  if (!user_access('administer nodes')) {
    $form['field_org_flag_featured']['#access'] = FALSE;
    $form['field_org_logo_promotional']['#access'] = FALSE;
    $form['field_org_high_promo_txt_section']['#access'] = FALSE;
  }
}

/**
 * Custom afterbuild function to manage additional contact field collection.
 */
function esf_tc_content_types_field_org_additional_contacts_after_build($form, &$form_state) {
  // Additional contact states.
  foreach ($form as $k => $v) {
    if (isset($v['#entity_type']) && $v['#entity_type'] == 'field_collection_item') {
      $form[$k]['field_fc_org_contact']['#states'] = array(
        'required' => array(
          ':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'yes'),
        ),
        'visible' => array(
          ':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'yes'),
        ),
      );

      $form[$k]['field_fc_org_name']['#states'] = array(
        'required' => array(
          ':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'no'),
        ),
        'visible' => array(
          ':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'no'),
        ),
      );

      $form[$k]['field_fc_org_email']['#states'] = array(
        'required' => array(
          ':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'no'),
        ),
        'visible' => array(
          ':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'no'),
        ),
      );

      $form[$k]['field_fc_org_role']['#states'] = array(
        'required' => array(
          array(':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'no')),
          'or',
          array(':input[name="field_org_additional_contacts[und][' . $k . '][field_fc_contact_account][und]"]' => array('value' => 'yes')),

        ),
      );
    }
  }

  return $form;
}

/**
 * Add custom organisation node form validation.
 */
function esf_tc_content_types_organisation_validate($form, &$form_state) {
  // Check Other organisation value.
  if (!empty($form_state['values']['field_org_type_of_organisation'][LANGUAGE_NONE])) {
    $tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'organisation_types');
    if ($tid != NULL) {
      if ($form_state['values']['field_org_type_of_organisation'][LANGUAGE_NONE][0]['tid'] == $tid && empty($form_state['values']['field_org_specify_type'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_org_specify_type', t('!name field is required.', array('!name' => $form['field_org_specify_type'][LANGUAGE_NONE]['#title'])));
      }
    }
  }

  // Check Other country value.
  if (!empty($form_state['values']['field_esf_country_ref'][LANGUAGE_NONE])) {
    $tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'esf_countries_regions');
    if ($tid != NULL) {
      if ($form_state['values']['field_esf_country_ref'][LANGUAGE_NONE][0]['tid'] == $tid && empty($form_state['values']['field_org_other_countries'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_org_other_countries', t('!name field is required.', array('!name' => $form['field_org_other_countries'][LANGUAGE_NONE]['#title'])));
      }
    }
  }

  // Check required values if the node (editorial status) is published.
  $status_fieldname = _esf_tc_content_types_get_editorial_status_field_name();
  $status = $form_state['values'][$status_fieldname][LANGUAGE_NONE][0]['value'];
  if ($form_state['values']['op'] == 'Publish' || ($form_state['values']['op'] == 'Save' && $status == 'published')) {
    // Legal contact.
    if ($form_state['values']['field_org_contact_account'][LANGUAGE_NONE][0]['value'] == 'yes' && empty($form_state['values']['field_org_contact'][LANGUAGE_NONE][0]['target_id'])) {
      form_set_error('field_org_contact', t('!name field is required.', array('!name' => $form['field_org_contact'][LANGUAGE_NONE]['#title'])));
    }
    elseif ($form_state['values']['field_org_contact_account'][LANGUAGE_NONE][0]['value'] == 'no') {
      if (empty($form_state['values']['field_org_contact_legal_name'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_org_contact_legal_name', t('!name field is required.', array('!name' => $form['field_org_contact_legal_name'][LANGUAGE_NONE]['#title'])));
      }
      if (empty($form_state['values']['field_org_contact_legal_email'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_org_contact_legal_email', t('!name field is required.', array('!name' => $form['field_org_contact_legal_email'][LANGUAGE_NONE]['#title'])));
      }
    }

    // Legal contact.
    if (!empty($form_state['values']['field_org_contact_legal_email'][LANGUAGE_NONE][0]['value'])) {
      $email_value = $form_state['values']['field_org_contact_legal_email'][LANGUAGE_NONE][0]['value'];
      if (!valid_email_address($email_value)) {
        form_set_error('field_org_contact_legal_email', t('!email is not a valid email.', array('!email' => $email_value)));
      }
    }
    // Additional contact.
    $contacts = $form_state['values']['field_org_additional_contacts'][LANGUAGE_NONE];
    foreach ($contacts as $key => $contact) {
      if (is_numeric($key) && empty($contact['field_fc_org_name'][LANGUAGE_NONE][0]['value']) && $contact['field_fc_contact_account'][LANGUAGE_NONE][0]['value'] == 'no') {
        form_set_error('field_fc_org_name', t('!name field is required.', array('!name' => $form['field_org_additional_contacts'][LANGUAGE_NONE][0]['field_fc_org_name'][LANGUAGE_NONE]['#title'])));
      }

      if (is_numeric($key) && empty($contact['field_fc_org_email'][LANGUAGE_NONE][0]['value']) && $contact['field_fc_contact_account'][LANGUAGE_NONE][0]['value'] == 'no') {
        form_set_error('field_fc_org_email', t('!name field is required.', array('!name' => $form['field_org_additional_contacts'][LANGUAGE_NONE][0]['field_fc_org_email'][LANGUAGE_NONE]['#title'])));
      }

      if (is_numeric($key) && !empty($contact['field_fc_org_email'][LANGUAGE_NONE][0]['value']) && $contact['field_fc_contact_account'][LANGUAGE_NONE][0]['value'] == 'no' && !valid_email_address($contact['field_fc_org_email'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_fc_org_email', t('!email is not a valid email.', array('!email' => $contact['field_fc_org_email'][LANGUAGE_NONE][0]['value'])));
      }
      if (is_numeric($key) && empty($contact['field_fc_org_contact'][LANGUAGE_NONE][0]['target_id']) && $contact['field_fc_contact_account'][LANGUAGE_NONE][0]['value'] == 'yes') {
        form_set_error('field_fc_org_contact', t('!name field is required.', array('!name' => $form['field_org_additional_contacts'][LANGUAGE_NONE][0]['field_fc_org_contact'][LANGUAGE_NONE]['#title'])));
      }

      if (is_numeric($key) && empty($contact['field_fc_org_role'][LANGUAGE_NONE][0]['value']) && !empty($contact['field_fc_contact_account'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_fc_org_role', t('!name field is required.', array('!name' => $form['field_org_additional_contacts'][LANGUAGE_NONE][0]['field_fc_org_role'][LANGUAGE_NONE]['#title'])));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter project node form.
 */
function esf_tc_content_types_form_esf_tnc_project_node_form_alter(&$form, &$form_state, $form_id) {

  // Add custom validate function.
  $form['#validate'][] = 'esf_tc_content_types_projects_database_draft_validate';
  $form['#validate'][] = 'esf_tc_content_types_project_validate';

  // Hide body field.
  $form['body']['#access'] = FALSE;

  // Other countries field states.
  $other_country_term_tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'esf_countries_regions');
  if ($other_country_term_tid != NULL) {
    $form['field_project_other_countries']['#states'] = array(
      'visible' => array(
        ':input[name="field_esf_country_ref[und]"]' => array('value' => $other_country_term_tid),
      ),
      'required' => array(
        ':input[name="field_esf_country_ref[und]"]' => array('value' => $other_country_term_tid),
      ),
    );
  }

  // Add callback to display calls per selected country.
  $form['field_esf_country_ref'][LANGUAGE_NONE]['#ajax'] = array(
    'callback' => '_esf_tc_content_types_project_country_callback',
    'event' => 'change',
    'wrapper' => 'call_involved_div',
  );

  // Add callback to warn user that the deadline date is a past date.
  $form['field_project_end_date_activity'][LANGUAGE_NONE][0]['#ajax'] = array(
    'callback' => '_esf_tc_content_types_projects_end_date_callback',
    'event' => 'change',
    'method' => 'html',
    'wrapper' => 'end_date_div',
  );

  // Manage field to be replace after callback.
  $selected_country = isset($form_state['values']['field_esf_country_ref'][LANGUAGE_NONE][0]) ? $form_state['values']['field_esf_country_ref'][LANGUAGE_NONE][0]['tid'] : $form['field_esf_country_ref'][LANGUAGE_NONE]['#default_value'];
  $call_default_value = '';
  if (isset($form_state['values']['field_project_call_for_projects'])) {
    $call_default_value = $form_state['values']['field_project_call_for_projects'];
  }
  elseif (isset($form['field_project_call_for_projects'][LANGUAGE_NONE]['#default_value'][0])) {
    $call_default_value = $form['field_project_call_for_projects'][LANGUAGE_NONE]['#default_value'][0];
  }

  $form['field_project_call_for_projects'][LANGUAGE_NONE]['#prefix'] = '<div id="call_involved_div">';
  $form['field_project_call_for_projects'][LANGUAGE_NONE]['#suffix'] = '</div>';
  $form['field_project_end_date_activity'][LANGUAGE_NONE][0]['#suffix'] = '<div id="end_date_div"></div>';
  $form['field_project_call_for_projects'][LANGUAGE_NONE]['#options'] = _esf_tc_content_types_get_calls_by_country_options($selected_country);
  $form['field_project_call_for_projects'][LANGUAGE_NONE]['#default_value'] = $call_default_value;
}

/**
 * Custom callback to display MA per selected country.
 *
 * @param array $form
 *    The form needed for ajax.
 * @param array $form_state
 *    The form state needed for ajax.
 *
 * @return array|mixed
 *    Return the field target fot Ajax refresh.
 */
function _esf_tc_content_types_project_country_callback($form, $form_state) {
  return $form['field_project_call_for_projects'];
}

/**
 * Custom callback to alert user which select a past date.
 *
 * @param array $form
 *    The form parameters.
 * @param array $form_state
 *    The form parameters.
 *
 * @return string
 *    Return warning message if past date selected.
 */
function _esf_tc_content_types_projects_end_date_callback($form, $form_state) {
  $return = '<div id="end_date_div"></div>';
  $datetime = new DateTime('today');
  $message = t('You selected a past date');

  if ($form_state['values']['field_project_end_date_activity'][LANGUAGE_NONE][0]['value'] < $datetime->getTimestamp()) {
    $return = '<div id="end_date_div"><div class="messages warning">' . $message . '</div></div>';
  }

  return $return;
}

/**
 * Return all calls for project per country as list options.
 *
 * @param int $country_tid
 *    The taxonomy ID of the country.
 *
 * @return array
 *    related call of projects options.
 */
function _esf_tc_content_types_get_calls_by_country_options($country_tid) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title'));
  $query->join('field_data_field_esf_country_ref', 'c', 'n.nid = c.entity_id');
  $query->condition('n.type', 'esf_tnc_call_for_project', '=')
    ->condition('c.field_esf_country_ref_tid', $country_tid)
    ->condition('n.status', 1);
  $query->orderBy('n.title', 'ASC');
  $result = $query->execute();

  // Add default 1st entry ('select a value').
  $options = array('_none' => t('- Select a value -'));
  foreach ($result as $call) {
    $options[$call->nid] = $call->title;
  }

  return $options;
}

/**
 * Add custom project node form validation.
 */
function esf_tc_content_types_project_validate($form, &$form_state) {
  // Check Other country value.
  if (!empty($form_state['values']['field_esf_country_ref'][LANGUAGE_NONE])) {
    $tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'esf_countries_regions');
    if ($tid != NULL) {
      if ($form_state['values']['field_esf_country_ref'][LANGUAGE_NONE][0]['tid'] == $tid && empty($form_state['values']['field_project_other_countries'][LANGUAGE_NONE][0]['value'])) {
        form_set_error('field_project_other_countries', t('!name field is required.', array('!name' => $form['field_project_other_countries'][LANGUAGE_NONE]['#title'])));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter call for call of project node form.
 */
function esf_tc_content_types_form_esf_tnc_call_for_project_node_form_alter(&$form, &$form_state) {

  // Add advice in message queue.
  if (!isset($form_state['input']['ajax_html_ids']) && !isset($form['#node']->nid)) {
    _esf_tc_content_types_advice_message();
  }

  // Add custom after build and validate function.
  $form['#after_build'][] = '_esf_tc_content_types_call_for_project_after_build';
  $form['#validate'][] = 'esf_tc_content_types_projects_database_draft_validate';

  // Hide body field.
  $form['body']['#access'] = FALSE;

  // Add callback to display MA per selected country.
  $form['field_esf_country_ref'][LANGUAGE_NONE]['#ajax'] = array(
    'callback' => '_esf_tc_content_types_call_country_callback',
    'event' => 'change',
    'wrapper' => 'org_involved_div',
  );

  // Manage field to be replace after callback.
  $selected_country = isset($form_state['values']['field_esf_country_ref']) ? $form_state['values']['field_esf_country_ref'][LANGUAGE_NONE][0]['tid'] : $form['field_esf_country_ref'][LANGUAGE_NONE]['#default_value'];
  $org_default_value = '';
  if (isset($form_state['values']['field_call_org_involved'])) {
    $org_default_value = $form_state['values']['field_call_org_involved'];
  }
  elseif (isset($form['field_call_org_involved'][LANGUAGE_NONE]['#default_value'][0])) {
    $org_default_value = $form['field_call_org_involved'][LANGUAGE_NONE]['#default_value'][0];
  }
  $form['field_call_org_involved'][LANGUAGE_NONE]['#prefix'] = '<div id="org_involved_div">';
  $form['field_call_org_involved'][LANGUAGE_NONE]['#suffix'] = '</div>';
  $form['field_call_org_involved'][LANGUAGE_NONE]['#options'] = _esf_tc_content_types_get_organisations_by_country_options($selected_country);
  $form['field_call_org_involved'][LANGUAGE_NONE]['#default_value'] = $org_default_value;
}

/**
 * Custom callback to display MA per selected country.
 *
 * @param array $form
 *    The form needed for ajax.
 * @param array $form_state
 *    The form state needed for ajax.
 *
 * @return array|mixed
 *    Return the field target fot Ajax refresh.
 */
function _esf_tc_content_types_call_country_callback($form, $form_state) {
  return $form['field_call_org_involved'];
}

/**
 * Custom after build function for call for project.
 *
 * @param array $form
 *    The form subject to after build.
 * @param array $form_state
 *    The form state subject to after build.
 *
 * @return mixed
 *    Return the modified form.
 */
function _esf_tc_content_types_call_for_project_after_build($form, &$form_state) {
  // Remove Other option form country list.
  $other_country_term_tid = _esf_tc_content_types_get_term_id_by_vocabulary('Other', 'esf_countries_regions');
  if ($other_country_term_tid) {
    unset($form['field_esf_country_ref'][LANGUAGE_NONE][0][$other_country_term_tid]);
  }
  return $form;
}

/**
 * Return all organisations per country as list options.
 *
 * @param int $country_tid
 *    The taxonomy ID of the country.
 *
 * @return array
 *    Return all related organisations as a list of options.
 */
function _esf_tc_content_types_get_organisations_by_country_options($country_tid) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title'));
  $query->join('field_data_field_org_is_ma_ib', 't', 'n.nid = t.entity_id');
  $query->join('field_data_field_esf_country_ref', 'c', 'n.nid = c.entity_id');
  $query->condition('t.field_org_is_ma_ib_value', 1)
    ->condition('c.field_esf_country_ref_tid', $country_tid)
    ->condition('n.status', 1);
  $query->orderBy('n.title', 'ASC');
  $result = $query->execute();

  // Add default 1st entry ('select a value').
  $options = array('_none' => t('- Select a value -'));
  foreach ($result as $org) {
    $options[$org->nid] = $org->title;
  }

  return $options;
}

/**
 * Project database (4 content types) custom validation for drafting.
 */
function esf_tc_content_types_projects_database_draft_validate(&$form, &$form_state) {
  $editorial_field_name = _esf_tc_content_types_get_editorial_status_field_name();
  $state = isset($form_state['values'][$editorial_field_name][LANGUAGE_NONE]) ? reset($form_state['values'][$editorial_field_name][LANGUAGE_NONE])['value'] : NULL;

  $errors = form_get_errors();

  // Only skip validation on Save as Draft of a drafted content.
  if ($state == 'draft' && isset($form_state['clicked_button']) && $form_state['clicked_button']['#value'] == 'Save as draft') {
    if ($errors) {
      // Clear errors.
      form_clear_error();
      // Remove error messages.
      drupal_get_messages('error');
      $removed_messages = array();

      foreach ($errors as $name => $error_message) {
        // Get Field title.
        $field_name = explode(']', $name)[0];
        $is_date = FALSE;
        $required_error = '';

        if ($field_name) {
          $field_info = field_info_field($field_name);
          $field_instance = field_info_instance($form['#entity_type'], $field_name, $form['#bundle']);
          $required_error = t('!name field is required.', array('!name' => $field_instance['label']));
          $is_date = $field_info['module'] == 'date';
        }
        if (strstr($name, 'title_field]') === FALSE && ($required_error == $error_message || $is_date)) {
          $removed_messages[] = $error_message;
          unset($errors[$name]);
        }
        else {
          form_set_error($name, $error_message);
        }
      }
    }
  }
}

/**
 * Project database (4 content types) custom submit for editorial status.
 */
function esf_tc_content_types_projects_database_submit(&$form, &$form_state) {
  $arr_status = _esf_tc_content_types_get_status();

  $field_esf_editorial_status = _esf_tc_content_types_get_editorial_status_field_name();

  if (isset($form_state['clicked_button']['#value'])) {
    $action = drupal_strtolower($form_state['clicked_button']['#value']);
  }
  $new_status = (isset($arr_status[$action])) ? $arr_status[$action] : NULL;
  if ($action && ($new_status != 'draft')) {
    if ($new_status != 'negotiation') {
      // Force publish drupal status.
      $form_state['status'] = $form_state['values']['status'] = 1;
    }
    else {
      $form_state['status'] = $form_state['values']['status'] = 0;
    }
    // Force Editorial status.
    if ($new_status) {
      $form_state['values'][$field_esf_editorial_status][LANGUAGE_NONE][0]['value'] = $new_status;
    }
  }
}

/**
 * Implements hook_node_access_records().
 */
function esf_tc_content_types_node_access_records($node) {
  $grants = array();

  // Denied access for non-public forum node per forum thematics.
  // Update and delete grants are managed by WB Access and basic permissions.
  if (is_object($node) && $node->type == 'forum') {
    $visibility = field_get_items('node', $node, 'field_topic_public', LANGUAGE_NONE);
    $public = reset($visibility)['value'];
    if (!$public) {
      $forum_section_field = field_get_items('node', $node, 'taxonomy_forums', LANGUAGE_NONE);
      $forum_section = $forum_section_field[0]['tid'];
      $grants[] = array(
        'realm' => 'forum_private',
        'gid' => $forum_section,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }
  }
  // ADD user access to referenced users into the project db content type.
  $content_types = _esf_tc_content_types_get_project_database_types();

  if (in_array($node->type, $content_types)) {
    $uids = array();
    $nids = array();
    switch ($node->type) {
      case 'esf_tnc_organisation':
        // LEGAL CONTACT.
        $uids += _esf_tc_content_types_get_references_ids('field_org_contact', $node);
        // ADDITIONAL CONTACTS.
        $contacts = field_get_items('node', $node, 'field_org_additional_contacts');
        if (is_array($contacts) && count($contacts)) {
          $cfids = array();
          foreach ($contacts as $contact) {
            $cfids[] = $contact['value'];
          }
          unset($contact);
          if (is_array($cfids) && count($cfids)) {
            $contacts = field_collection_item_load_multiple($cfids);
            foreach ($contacts as $contact) {
              $uids = array_merge($uids, _esf_tc_content_types_get_references_ids('field_fc_org_contact', $contact, 'field_collection_item'));
            }
            unset($contact);
          }
        }
        break;

      case 'esf_tnc_project':
        // Get Lead organisation contact.
        $nids = array_merge($nids, _esf_tc_content_types_get_references_ids('field_project_lead_organisation', $node));
        // Get Projects Managers ID.
        $uids = array_merge($uids, _esf_tc_content_types_get_references_ids('field_project_manager', $node));
        // Get Operational Contact ID.
        $uids = array_merge($uids, _esf_tc_content_types_get_references_ids('field_project_operat_contact', $node));
        break;

      case 'esf_tnc_tca':
        $tca_wrapper = entity_metadata_wrapper('node', $node);
        // Get Main contact organisation.
        $nids = array_merge($nids, _esf_tc_content_types_get_references_ids('field_tca_main_contact_point', $node));
        // GET MAs.
        $mas = array();
        // Projects partners.
        foreach ($tca_wrapper->field_tca_partner_organisations->getIterator() as $partner) {
          if (!empty($partner->field_fc_partner_project->value())) {
            $project = $partner->field_fc_partner_project->value();
            if (!empty($project)) {
              // Get Lead organisation contact.
              $nids = array_merge($nids, _esf_tc_content_types_get_references_ids('field_project_lead_organisation', $project));
              // Get Projects Managers ID.
              $uids = array_merge($uids, _esf_tc_content_types_get_references_ids('field_project_manager', $project));
              // Get Operational Contact ID.
              $uids = array_merge($uids, _esf_tc_content_types_get_references_ids('field_project_operat_contact', $project));
              // Get Projects Managing Authorities.
              $mas = array_merge($mas, _esf_tc_content_types_get_responsible_authorities($project->type, $project));
            }
          }
        }
        unset($partner);
        break;

    }
    // Define realm.
    $grants_template = array(
      'grant_view' => 1,
      'grant_update' => 1,
      'grant_delete' => 0,
      'priority' => 0,
    );
    // Define realm projectdb User.
    $uids = array_unique($uids);
    // Grant edit to author if not included.
    if (!in_array($node->uid, $uids)) {
      $uids[] = $node->uid;
    }
    if (is_array($uids) && count($uids)) {
      $grants_template['realm'] = 'projectdb';
      foreach ($uids as $uid) {
        $grants_template['gid'] = $uid;
        $grants[] = $grants_template;
      }
      unset($uid);
    }
    // Define realm projectdb Organisation.
    $nids = array_unique($nids);
    if (is_array($nids) && count($nids)) {
      $grants_template['realm'] = 'projectdb_organisation';
      foreach ($nids as $nid) {
        $grants_template['gid'] = $nid;
        $grants[] = $grants_template;
      }
      unset($nid);
    }
    // Define MA ACCESS.
    if (!empty($mas) && count($mas)) {
      $mas = array_unique($mas);
      $grants_template = array(
        'realm' => 'projectdb_mas',
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );
      foreach ($mas as $ma) {
        $grants_template['gid'] = $ma;
        $grants[] = $grants_template;
      }
      unset($ma);
    }
    // View published content by anonymous.
    if ($node->status) {
      $grants[] = array(
        'realm' => 'projectdb_published',
        'gid' => 1,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 0,
      );
    }
  }
  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function esf_tc_content_types_node_grants($account, $op) {
  $grants = array();
  if ($account->uid) {
    if ($op == 'view') {
      // Check permission access to forum section.
      $wb_user_access_tree = workbench_access_get_user_tree($account);
      if (!empty($wb_user_access_tree)) {
        foreach ($wb_user_access_tree as $key => $term) {
          $grants['forum_private'][] = $key;
        }
      }
    }
    $grants['projectdb'][] = $account->uid;
    // Related organisations.
    $org = _esf_tc_content_type_get_organisation($account->uid);
    if (is_array($org) && count($org)) {
      $grants['projectdb_organisation'] = $org;
      $grants['projectdb_mas'] = $org;
    }
  }
  $grants['projectdb_published'][] = intval(user_access('access content'));
  return $grants;
}

/**
 * Implements template_preprocess_forums().
 */
function esf_tc_content_types_preprocess_forums(&$variables) {
  // Add custom content to forum page.
  if ($variables['tid'] != 0) {
    $variables['topics_title'] = t('Discussions');
    $variables['articles'] = _esf_tc_content_types_render_view('esf_tn_articles', 'block_1', $variables['tid']);
    $variables['news'] = _esf_tc_content_types_render_view('esf_news', 'block_1', $variables['tid']);
    $variables['events'] = _esf_tc_content_types_render_view('esf_events', 'block_1', $variables['tid']);
    $variables['action_links'] = menu_local_actions();
  }
}

/**
 * Render view for events and news block.
 *
 * @param string $view_name
 *    The name of view used for rendering.
 * @param string $view_display
 *    The display of view used for rendering.
 * @param string $param
 *    Additionals parameters.
 *
 * @return string
 *    Return output of view.
 */
function _esf_tc_content_types_render_view($view_name, $view_display, $param) {
  $output = '';
  $view = views_get_view($view_name);
  $view->set_display($view_display);
  $view->set_arguments(array($param));
  $view->pre_execute();
  $view->execute();
  if (!empty($view->result)) {
    $output = $view->render();
  }
  return $output;
}

/**
 * Implements hook_menu().
 */
function esf_tc_content_types_menu() {
  $items = array();

  $_type = array(
    'organisation' => 'Manage notifications for the organisations',
    'project' => 'Manage notifications for the projects',
    'tca' => 'Manage notifications for the TCA',
  );

  $item_template = array(
    'access arguments' => array('administer nodes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('esf_tc_content_state_notification_form', 3),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'esf_tc_content_types.notification.inc',
  );

  // Notifications.
  $items['admin/config/esf-notifications'] = array(
    'title' => 'ESF Notifications',
    'description' => 'Manage email notifications.',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer nodes'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  foreach ($_type as $type => $description) {
    $item = $item_template;
    $item['title'] = drupal_ucfirst($type);
    $item['description'] = $description;
    $items['admin/config/esf-notifications/' . $type] = $item;
  }
  unset($type, $description);

  $items['esf/notify/contact/%/%node/%/%/%'] = array(
    'title' => 'ESF notify contact',
    'type' => MENU_CALLBACK,
    'page callback' => '_esf_tc_content_types_notify_contact',
    'page arguments' => array(3, 4, 5, 6, 7),
    'access callback' => 'user_is_logged_in',
  );
  $items['esf/tca/%node/partners/%field_collection_item/%'] = array(
    'title' => 'ESF tca project partners validation',
    'type' => MENU_CALLBACK,
    'page callback' => '_esf_tc_content_types_tca_partners_validation',
    'page arguments' => array(2, 4, 5),
    'access callback' => '_esf_tc_content_types_tca_partners_project_access',
    'access arguments' => array(4),
    'file' => 'esf_tc_content_types.tca.inc',
  );
  $items['whoswho'] = array(
    'title' => 'Who\'s who',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => '_esf_tc_content_types_whoswho_page',
    'file' => 'esf_tc_content_types.tca.inc',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function esf_tc_content_types_menu_alter(&$items) {
  $items['forum/%forum_forum/join'] = array(
    'title' => 'Join the network',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => '_esf_tc_content_types_manage_networking',
    'page arguments' => array(1, 2),
    'access callback' => 'user_is_logged_in',
  );

  $items['forum/%forum_forum/remove'] = array(
    'title' => 'Remove me from the newtork',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => '_esf_tc_content_types_manage_networking',
    'page arguments' => array(1, 2),
    'access callback' => 'user_is_logged_in',
  );
}

/**
 * Helper function get the editorial status field name.
 *
 * @return string
 *    Return the field name of the editorial status.
 */
function _esf_tc_content_types_get_editorial_status_field_name() {
  return variable_get('esf_tc_editorial_status_field_name', 'field_esf_editorial_status');
}

/**
 * Helper function get all content types used for Projects database.
 *
 * @return array
 *    Return a list of content types used for the projects databases.
 */
function _esf_tc_content_types_get_project_database_types() {
  return array(
    'esf_tnc_organisation',
    'esf_tnc_project',
    'esf_tnc_call_for_project',
    'esf_tnc_tca',
  );
}

/**
 * Helper function get all sentive data fields name.
 *
 * @return array
 *    Return a list of fields name.
 */
function _esf_tc_content_types_sensitive_data_fields($type) {
  switch ($type) {
    case 'esf_tnc_organisation':
      $fields = array(
        'field_esf_country_ref',
        'field_org_name_national_lang',
      );
      break;

    case 'esf_tnc_project':
      $fields = array(
        'field_esf_country_ref',
        'field_project_call_for_projects',
        'field_project_lead_organisation',
      );
      break;

    case 'esf_tnc_tca':
      $fields = array(
        'title',
        'field_tca_budget',
        'field_tca_attach_budget_table',
        'field_tca_signed_agreement',
        'field_tca_objectives',
        'field_tca_work_pgm',
        'field_tca_decision',
      );
      break;
  }
  return $fields;
}

/**
 * Helper function get all editorial status.
 *
 * @return array
 *    Return a list of button label keys and their related editorial status.
 */
function _esf_tc_content_types_get_status() {
  return array(
    'publish' => 'published',
    'block' => 'blocked',
    'archive' => 'archived',
    'ask for deletion' => 'needs-deletion',
    'submit to ib/ma for validation' => 'negotiation',
  );
}

/**
 * Helper function to check if user can access to the actions button.
 *
 * @param string $action
 *    The action of the button.
 * @param string $content_type
 *    The viewed content type.
 * @param string $node
 *    The viewed node.
 * @param string $status
 *    The current status of the content.
 *
 * @return bool
 *    Return if the current user can access to the action button.
 */
function _esf_tc_content_types_button_access($action, $content_type, $node, $status = NULL) {
  $content_types = _esf_tc_content_types_get_project_database_types();
  $editorial_status_field_name = _esf_tc_content_types_get_editorial_status_field_name();

  // Find status if not defined.
  if (!$status) {
    $status = field_get_items('node', $node, $editorial_status_field_name);
    if (is_array($status)) {
      $status = reset($status)['value'];
    }
  }
  if (in_array($content_type, $content_types)) {
    switch ($action) {
      case 'block':
        if (in_array($status, array(
          'published',
          'archived',
          'needs-deletion',
          'negotiate',
        ))) {
          if (user_access("block any $content_type content")) {
            return TRUE;
          }
          else {
            // Get all managing authorities linked and check current user.
            $mas = _esf_tc_content_types_get_responsible_authorities($content_type, $node);
            return _esf_tc_content_types_ma_access($mas);
          }
        }
        break;

      case 'archive':
        if (in_array($status, array('published', 'negotiation'))) {
          return user_access("archive any $content_type content");
        }
        break;

      case 'needs-deletion':
        if (!in_array($status, array('needs-deletion'))) {
          if (node_access('update', $node)) {
            return TRUE;
          }
          else {
            // Get all managing authorities linked and check current user.
            $mas = _esf_tc_content_types_get_responsible_authorities($content_type, $node);
            return _esf_tc_content_types_ma_access($mas);
          }
        }
        break;

      case 'publish':
        if ($status == 'draft') {
          return TRUE;
        }
        elseif (in_array($status, array(
          'blocked',
          'archived',
          'needs-deletion',
        ))) {
          if (user_access("republish any $content_type content")) {
            return TRUE;
          }
          elseif ($status == 'blocked') {
            // Get all managing authorities linked and check current user.
            $mas = _esf_tc_content_types_get_responsible_authorities($content_type, $node);
            return _esf_tc_content_types_ma_access($mas);
          }
        }
        break;

      case 'submit':
        if ($status != 'archived') {
          return TRUE;
        }
        break;

      case 'negotiation':
        return TRUE;

    }
  }
  return FALSE;
}

/**
 * Helper function to get the Managing Authorities linked to the node.
 *
 * @param string $content_type
 *    The content type used to find responsible authorities.
 * @param object $node
 *    The node used to find responsible authorities.
 *
 * @return array
 *    Return nodes of associated Managing authorities.
 */
function _esf_tc_content_types_get_responsible_authorities($content_type, $node) {
  $content_types = _esf_tc_content_types_get_project_database_types();

  if (in_array($content_type, $content_types) && $content_type != 'esf_tnc_tca') {
    $sql = db_select('field_data_field_org_is_ma_ib', 'MA')
      ->fields('MA', array('entity_id'))
      ->condition('field_org_is_ma_ib_value', '1');

    $sql->join('field_data_field_call_org_involved', 'calls', 'calls.field_call_org_involved_target_id = MA.entity_id');
    switch ($content_type) {
      case 'esf_tnc_organisation':
        $sql->join('field_data_field_project_call_for_projects', 'project', 'project.field_project_call_for_projects_target_id = calls.entity_id');
        $sql->join('field_data_field_project_lead_organisation', 'pjtorg', 'pjtorg.field_project_lead_organisation_target_id = :nid', array(':nid' => intval($node->nid)));
        break;

      case 'esf_tnc_project':
        // Init Call ID.
        $cid = 0;
        if (isset($node->field_project_call_for_projects[LANGUAGE_NONE][0]['target_id'])) {
          $cid = intval($node->field_project_call_for_projects[LANGUAGE_NONE][0]['target_id']);
        }
        $sql->join('field_data_field_project_call_for_projects', 'project', 'calls.entity_id = :cid', array(':cid' => $cid));
        break;
    }
    if ($sql) {
      $result = $sql->execute()
        ->fetchCol();
      if (!empty($result) && is_array($result)) {
        return array_unique($result);
      }
    }
  }
  return array();
}

/**
 * Helper function to check if current user is an Managing Authorities granted.
 *
 * @param array $mas
 *    The managing authorities to check.
 *
 * @return bool
 *    Return TRUE if Managing Authorities have update rights.
 */
function _esf_tc_content_types_ma_access($mas) {
  if (is_array($mas) && count($mas)) {
    foreach ($mas as $ma) {
      $ma = node_load($ma);
      if (node_access('update', $ma)) {
        return TRUE;
      }
    }
    unset($ma);
  }
  return FALSE;
}

/**
 * Notify the forum moderator.
 *
 * @param object $forum_term
 *    The taxonomy object of the forum used for network.
 * @param string $op
 *    The operation asked by user.
 */
function _esf_tc_content_types_manage_networking($forum_term, $op) {
  global $user;

  if ($op == 'join') {
    // Notify the forum moderator when asking to join.
    $emails = _esf_tc_content_types_get_forum_moderators($forum_term);
    if (empty($emails)) {
      drupal_set_message(t('There is currently no moderator for this network. Please contact the webmaster.'), 'warning');
    }
    else {
      rules_invoke_component('esf_tc_content_types_notify_forum_moderator_to_add_user', $user, $forum_term, $emails);
    }
  }
  elseif ($op == 'remove') {
    // Remove directly the user from the network.
    workbench_access_user_section_delete($user->uid, $forum_term->tid, 'taxonomy');
    drupal_set_message(t('Your access to the netowrk has been removed'));
  }

  // Redirect to forum page.
  drupal_goto(drupal_get_path_alias('forum/' . $forum_term->tid));
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function esf_tc_content_types_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  global $user;

  // Add local link to forum pages.
  if ($root_path == 'forum/%') {
    if (user_is_logged_in()) {
      $tid = (isset($router_item['page_arguments'][0]) ? $router_item['page_arguments'][0]->tid : 0);
      $forum_term = forum_forum_load($tid);
      if ($forum_term) {
        // Get the access tree for the user account.
        $user_access_tree = workbench_access_get_user_tree($user);

        // Add specific action link regarding the user is already member
        // of the network or not.
        $links = array();
        if (!array_key_exists($tid, $user_access_tree)) {
          $links['forum_join'] = array(
            '#theme' => 'menu_local_action',
            '#link' => array(
              'title' => t('Join this network'),
              'href' => 'forum/' . $forum_term->tid . '/join',
            ),
          );
        }
        else {
          $links['forum_remove'] = array(
            '#theme' => 'menu_local_action',
            '#link' => array(
              'title' => t('Remove me from this network'),
              'href' => 'forum/' . $forum_term->tid . '/remove',
            ),
          );
        }
        $data['actions']['output'] = $links;
      }
    }
  }
}

/**
 * Get emails of moderators by forum.
 *
 * @param object $forum_term
 *    The taxonomy object used for network.
 *
 * @return array
 *    Return the emails of network moderators.
 */
function _esf_tc_content_types_get_forum_moderators($forum_term) {
  $moderator_rid = ($role = user_role_load_by_name('forum moderator')) ? $role->rid : NULL;

  // Retrieve the moderators' emails of the network.
  $query = db_select('users', 'u')
    ->fields('u', array('uid', 'mail'));
  $query->join('workbench_access_user', 'wau', 'u.uid = wau.uid');
  $query->join('users_roles', 'ur', 'u.uid = ur.uid');
  $query->condition('wau.access_scheme', 'taxonomy')
    ->condition('wau.access_id', $forum_term->tid)
    ->condition('ur.rid', $moderator_rid);
  $result = $query->execute();

  $emails = array();
  foreach ($result as $account) {
    $emails[] = $account->mail;
  }
  return $emails;
}

/**
 * Return tid of a term in a specific vocabulary.
 *
 * @param object $term
 *    The term to treat.
 * @param object $vocabulary
 *    The vocabulary associed to the term.
 *
 * @return int
 *    Return the term ID of other country if exists.
 */
function _esf_tc_content_types_get_term_id_by_vocabulary($term, $vocabulary) {
  $tid = NULL;
  $term_other_country = taxonomy_get_term_by_name($term, $vocabulary);
  if (!empty($term_other_country)) {
    $tid = array_pop($term_other_country)->tid;
  }
  return $tid;
}

/**
 * Implements hook_user_insert().
 */
function esf_tc_content_types_user_insert(&$edit, $account, $category) {
  // Add default role to user if he have only authenticated role.
  if (count($account->roles) == 1) {
    $default_role = user_role_load_by_name('contact');
    if (!empty($default_role->rid) && intval($default_role->rid)) {
      $account->roles[$default_role->rid] = $default_role;
    }
  }
  // Associate the default sections to the new user.
  _esf_tc_content_types_user_set_default_sections($account);
}

/**
 * Implements hook_user_login().
 */
function esf_tc_content_types_user_login(&$edit, $account) {
  if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset' || variable_get('login_destination_immediate_redirect', FALSE)) {
    // Redirect an authenticated only user or contact user to the profile page
    // if no profile attached to user.
    // Add the role contact to the authenticated only user.
    if (in_array('contact', $account->roles) || count($account->roles) == 1) {
      if (count($account->roles) == 1) {
        $user = user_load($account->uid);
        $role = user_role_load_by_name('contact');
        $user->roles = $user->roles + array($role->rid => $role->name);
        user_save($user);
      }

      $contact_profile = profile2_load_by_user($account, 'contact_profile');
      if (empty($contact_profile)) {
        drupal_set_message(t('You have been redirected to fill out your contact information. You can also enter the token received in the email to link your account with an organisation.'));
        drupal_goto("user/$account->uid/edit/contact_profile");
      }
    }
  }
}

/**
 * Helper to add default workbench access sections to a user.
 *
 * @param mixed $account
 *    The id or account (object) of targered user.
 */
function _esf_tc_content_types_user_set_default_sections($account) {

  // Load user if only uid.
  if (is_int($account)) {
    $uid = $account;
    $account = user_load($uid);
  }
  else {
    $uid = $account->uid;
  }

  $default_forums = array(
    'ESF Transnationality',
    'Discussions on projects',
    'Technical support',
  );

  $default_role = user_role_load_by_name('contact');
  $rid = $default_role->rid;

  if ($account && user_has_role($rid, $account)) {
    $tids = array();

    foreach ($default_forums as $forum) {
      if (($tax = taxonomy_get_term_by_name($forum)) && $tid = key($tax)) {
        $tids[] = $tid;
      }
    }
    unset($forum);
    if (!empty($uid) && !empty($tids)) {
      workbench_access_rebuild_user($uid, $tids);
    }
  }
}

/**
 * Helper function to get entity references IDs.
 *
 * @param string $field_name
 *    The field name used to get references.
 * @param object $entity
 *    The entity having the references.
 * @param string $type
 *    The type of the entity having references.
 *
 * @return array
 *    Return all user ID references into the field.
 */
function _esf_tc_content_types_get_references_ids($field_name, $entity, $type = 'node') {
  $uids = array();
  $contacts = field_get_items($type, $entity, $field_name);
  if (is_array($contacts)) {
    foreach ($contacts as $contact) {
      if (isset($contact['target_id']) && $contact['target_id']) {
        $uids[] = $contact['target_id'];
      }
    }
    unset($contact);
  }
  return $uids;
}

/**
 * Helper function to get all organisation of a user.
 *
 * @param int $uid
 *    The user ID target.
 *
 * @return array
 *    Return all organisation IDs where the user is referenced.
 */
function _esf_tc_content_type_get_organisation($uid) {
  $nids = array();
  // Lead organisations.
  $select = db_select('field_data_field_org_contact', 'c')
    ->fields('c', array('entity_id'))
    ->condition('bundle', 'esf_tnc_organisation')
    ->condition('field_org_contact_target_id', $uid)
    ->execute()
    ->fetchCol();

  if (is_array($select) && count($select)) {
    $nids += $select;
  }
  // Additional contacts.
  $sql = db_select('field_data_field_fc_org_contact', 'fcc')
    ->condition('field_fc_org_contact_target_id', $uid)
    ->condition('fcc.bundle', 'field_org_additional_contacts');
  $sql->join('field_data_field_org_additional_contacts', 'cnt', 'cnt.field_org_additional_contacts_value = fcc.entity_id');
  $sql->fields('cnt', array('entity_id'));

  $select = $sql->execute()
    ->fetchCol();

  if (is_array($select) && count($select)) {
    $nids = array_merge($nids, $select);
  }

  $nids = array_unique($nids);
  return $nids;
}

/**
 * Helper function to display message on form when status is not published.
 *
 * @param object $node
 *    The node targered by message.
 * @param string $state
 *    The current status of the node.
 */
function _esf_tc_content_type_display_message($node, $state) {
  switch ($state) {
    case 'draft':
      $message = t('The status of this content is draft');
      if (!empty($node->type) && $node->type == 'esf_tnc_tca') {
        $message = t('The status of this content is draft. Don’t forget to submit it for approval to all the MAs/IBs when ready');
      }
      drupal_set_message($message, 'warning', TRUE);
      break;

    case 'blocked':
      drupal_set_message(t('This content is blocked, please contact the webmaster or the managing authority'), 'error', TRUE);
      break;

    case 'archived':
      drupal_set_message(t('This content is archived. Update is not allowed anymore'), 'warning', TRUE);
      break;

    case 'needs-deletion':
      drupal_set_message(t('This content is tagged as needs deletion. Please contact the webmaster if you need change the status'), 'error', TRUE);
      break;
  }
}

/**
 * Helper function to get all associated email to a node.
 *
 * @param object $node
 *    The node object targered.
 * @param bool $with_ma
 *    If TRUE the managing authorities is also returned.
 *
 * @return array
 *    Return the emails addresses of all users which are associated to the node.
 */
function _esf_tc_content_types_get_associated_email($node, $with_ma = FALSE) {
  $emails = array();
  $wrapper = entity_metadata_wrapper('node', $node);
  $is_ma = FALSE;

  switch ($node->type) {
    case 'esf_tnc_organisation':
      $is_ma = $wrapper->field_org_is_ma_ib->value();
      $choice = $wrapper->field_org_notif_choice->value();
      // Check who has to be notified.
      if ($choice) {
        if ($wrapper->field_org_notif_address->value()) {
          $emails[] = $wrapper->field_org_notif_address->value();
        }
      }
      else {
        // Legal contact.
        $has_account = field_get_items('node', $node, 'field_org_contact_account');
        if (is_array($has_account) && isset(reset($has_account)['value'])) {
          $has_account = reset($has_account)['value'];
        }
        if ($has_account == 'no') {
          $field_value = field_get_items('node', $node, 'field_org_contact_legal_email');
          if (is_array($field_value) && isset(reset($field_value)['value'])) {
            $emails[] = reset($field_value)['value'];
          }
        }
        elseif ($has_account == 'yes') {
          $uids = _esf_tc_content_types_get_references_ids('field_org_contact', $node);
          if (is_array($uids)) {
            foreach ($uids as $uid) {
              $user = user_load($uid);
              if ($user->mail) {
                $emails[] = $user->mail;
              }
            }
            unset($uid, $user);
          }
        }
      }

      break;

    case 'esf_tnc_project':
      // Lead organisation.
      $field_value = _esf_tc_content_types_get_references_ids('field_project_lead_organisation', $node);
      if (is_array($field_value) & count($field_value)) {
        $nid = reset($field_value);
        $lead = node_load($nid);
        $contacts = _esf_tc_content_types_get_associated_email($lead);
        if (count($contacts)) {
          $emails = array_merge($emails, $contacts);
        }
      }
      // Other contacts.
      $contact_uids = array_merge(_esf_tc_content_types_get_references_ids('field_project_manager', $node), _esf_tc_content_types_get_references_ids('field_project_operat_contact', $node));
      if (is_array($contact_uids) && count($contact_uids)) {
        $contacts = array();
        foreach (user_load_multiple($contact_uids) as $_user) {
          if ($_user->mail) {
            $contacts[] = $_user->mail;
          }
        }
        unset($_user);
      }
      if (is_array($contacts) && count($contacts)) {
        $emails = array_merge($emails, $contacts);
      }
      break;

    case 'esf_tnc_tca':
      $wrapper = entity_metadata_wrapper('node', $node);
      // Main contact organisation.
      $org = $wrapper->field_tca_main_contact_point->value();
      if ($org) {
        $contacts = _esf_tc_content_types_get_associated_email($org);
        if (count($contacts)) {
          $emails = array_merge($emails, $contacts);
        }
      }
      // Projects parnters.
      foreach ($wrapper->field_tca_partner_organisations->getIterator() as $partner) {
        try {
          if ($project = $partner->field_fc_partner_project->value()) {
            $contacts = _esf_tc_content_types_get_associated_email($project);
            if (count($contacts)) {
              $emails = array_merge($emails, $contacts);
            }
          }
        }
        catch (\Exception $e) {
          watchdog('partners_project', $e->getMessage(), array(), WATCHDOG_ERROR);
        }
      }
      unset($partner);
      break;
  }
  // Managing Authorities.
  if ($with_ma && !$is_ma) {
    $mas = _esf_tc_content_types_get_responsible_authorities($node->type, $node);
    if (is_array($mas) && count($mas)) {
      foreach ($mas as $ma) {
        $ma = node_load($ma);
        $contacts = _esf_tc_content_types_get_associated_email($ma, TRUE);
        if (count($contacts)) {
          $emails = array_merge($emails, $contacts);
        }
      }
      unset($ma, $contacts);
    }
  }

  return array_unique($emails);
}

/**
 * Helper function to get Webmasters emails.
 *
 * @param string $rolename
 *    The role used for the webmasters.
 *
 * @return mixed
 *    Return all emails of webmasters.
 */
function _esf_tc_content_types_get_webmasters_email($rolename = 'webmaster') {
  // Get Role rid.
  $role = user_role_load_by_name($rolename);
  if (is_object($role) && $rid = $role->rid) {
    $sql = db_select('users_roles', 'ur')
      ->fields('usr', array('mail'))
      ->condition('rid', $rid);
    $sql->join('users', 'usr', 'usr.uid = ur.uid');

    return $sql->execute()->fetchCol();
  }
}

/**
 * Implements hook_node_delete().
 */
function esf_tc_content_types_node_delete($node) {
  // Confirm delete notification.
  if (in_array($node->type, _esf_tc_content_types_get_project_database_types()) && $node->type != 'esf_tnc_call_for_project') {
    $emails = _esf_tc_content_types_get_associated_email($node, TRUE);
    $new_status = 'deleted';

    if (count($emails)) {
      // Get mail message.
      $options = array(
        'type' => 'editorial_status',
        'content_type' => $node->type,
        'action' => $new_status,
        'node' => $node,
      );
      $key_prefix = $node->type . '_notification_' . $new_status;

      foreach ($emails as $email) {
        if (valid_email_address($email)) {
          drupal_mail('esf_tc_content_types', $key_prefix, $email, language_default(), $options);
        }
      }
      unset($email);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter WB Access editor form.
 */
function esf_tc_content_types_form_workbench_access_editor_form_alter(&$form, &$form_state) {
  // Add description to better select a user.
  $form['add_user']['#description'] = t('Type first letters of a username.');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function esf_tc_content_types_preprocess_field(&$variables) {
  if ($variables['element']['#field_type'] == 'field_collection') {
    switch ($variables['element']['#field_name']) {
      case 'field_org_additional_contacts':
        if (is_array($variables['items']) && count($variables['items'])) {
          foreach ($variables['items'] as &$item) {
            $fc = reset($item['entity']['field_collection_item'])['#entity'];
            $fc_wrapper = entity_metadata_wrapper('field_collection_item', $fc);

            $has_account = $fc_wrapper->field_fc_contact_account->value();

            if ($has_account == 'yes') {
              $type = 'ecas';
              $account = $fc_wrapper->field_fc_org_contact->value();
              $name = format_username($account);
              $email = $account->mail;
            }
            else {
              $type = 'simple';
              $name = $fc_wrapper->field_fc_org_name->value();
              $email = $fc_wrapper->field_fc_org_email->value();
            }

            $role = $fc_wrapper->field_fc_org_role->value();
            $nid = $fc->hostEntityId();
            if (node_access('update', $fc->hostEntity())) {
              $item['links']['#links']['resend'] = array(
                'title' => t('Resend invitation'),
                'href' => drupal_encode_path(format_string('esf/notify/contact/@type/@nid/@name/@role/@email',
                  array(
                    '@type' => $type,
                    '@nid' => $nid,
                    '@name' => $name,
                    '@role' => $role,
                    '@email' => $email,
                  )
                )),
                'query' => array('destination' => current_path()),
                'attributes' => array(
                  'type' => 'message',
                  'class' => array('btn-danger'),
                ),
                'html' => FALSE,
              );
            }
          }
          unset($item);
        }
        break;

      case 'field_tca_partner_organisations':
        if (is_array($variables['items']) && count($variables['items'])) {
          foreach ($variables['items'] as &$item) {
            $fc = reset($item['entity']['field_collection_item'])['#entity'];
            $fc_wrapper = entity_metadata_wrapper('field_collection_item', $fc);
            $nid = $fc->hostEntityId();
            $tca = $fc->hostEntity();
            $tca_wrapper = entity_metadata_wrapper('node', $tca);

            // Get entity infos.
            $status = $fc_wrapper->field_fc_mas_approval_status->value();
            $tca_status = $tca_wrapper->field_esf_editorial_status->value();

            // Display button only if the status is ready
            // and TCA in negotiation.
            if ($status != 'pending-key-changes' && $tca_status != 'draft') {
              // Check if user is a webmaster or administrator.
              $access = _esf_tc_content_types_tca_partners_project_access($fc);
              // Add buttons.
              if ($access) {
                $item['links']['#links']['accept'] = array(
                  'title' => t('Accept'),
                  'href' => drupal_encode_path(format_string('esf/tca/@nid/partners/@fcid/accepted',
                    array(
                      '@nid' => $nid,
                      '@fcid' => $fc->item_id,
                    )
                  )),
                  'query' => array('destination' => current_path()),
                  'attributes' => array(
                    'class' => array('btn', 'btn-success'),
                  ),
                  'html' => FALSE,
                );
                $item['links']['#links']['reject'] = array(
                  'title' => t('Reject'),
                  'href' => drupal_encode_path(format_string('esf/tca/@nid/partners/@fcid/rejected',
                    array(
                      '@nid' => $nid,
                      '@fcid' => $fc->item_id,
                    )
                  )),
                  'query' => array('destination' => current_path()),
                  'attributes' => array(
                    'class' => array('btn', 'btn-danger'),
                  ),
                  'html' => FALSE,
                );
                $arr_status = array(
                  'accepted' => 'accept',
                  'rejected' => 'reject',
                );
                // Disable button if necessary.
                if (in_array($status, array_keys($arr_status))) {
                  $item['links']['#links'][$arr_status[$status]]['attributes']['disabled'] = 'disabled';
                  $item['links']['#links'][$arr_status[$status]]['attributes']['class'][] = 'disabled';
                }
              }
            }
          }
          unset($item);
        }
        break;
    }
  }
}

/**
 * Helper function to send notification to a contact.
 *
 * @param string $key
 *    The key used to generate email message.
 * @param object $node
 *    The node targered by the notification.
 * @param string $name
 *    The name of receiver.
 * @param string $role
 *    The role of the receiver.
 * @param string $email
 *    The email of the receiver.
 */
function _esf_tc_content_types_notify_contact($key, $node, $name, $role, $email) {
  $error = TRUE;
  $name = urldecode($name);
  $role = urldecode($role);
  $email = urldecode($email);

  if (isset($node->type)) {
    $options = array(
      'type' => 'contact',
      'content_type' => $node->type,
      'node' => $node,
      'contact' => array(
        'name' => $name,
        'role' => $role,
        'email' => $email,
      ),
    );

    $key_prefix = $node->type . '_notification_contact_' . $key;
    if (valid_email_address($email)) {
      drupal_mail('esf_tc_content_types', $key_prefix, $email, language_default(), $options);
      $error = FALSE;
    }
  }

  if ($error) {
    $message = t('The invitation could not be send');
    $type = 'error';
  }
  else {
    $message = t('The invitation was sent to @email', array('@email' => $email));
    $type = 'status';
  }
  drupal_set_message($message, $type);
  drupal_goto(drupal_get_destination());
}

/**
 * Implements hook_field_default_field_instances_alter().
 */
function esf_tc_content_types_field_default_field_instances_alter(&$fields) {
  // 4/3 default image.
  $variable_name = 'esf_tnc_4_3_default_image_fid';
  $fields_name = array(
    'esf_tnc_event' => 'field_esf_event_picture',
    'esf_tnc_news' => 'field_esf_news_picture',
  );

  foreach ($fields_name as $bundle => $field_name) {
    $identifier = 'node-' . $bundle . '-' . $field_name;
    if (isset($fields[$identifier]['settings']['default_image'])) {
      $current_fid = $fields[$identifier]['settings']['default_image'];
      $fields[$identifier]['settings']['default_image'] = variable_get($variable_name, $current_fid);
    }
  }
  unset($bundle, $field_name);
}

/**
 * Helper function to add an advice message on node creation.
 *
 * @param string $type
 *    The machine name of the targered content type.
 */
function _esf_tc_content_types_advice_message($type = NULL) {
  if ($type == 'esf_tnc_tca') {
    $message = '<p>' . t('Please ensure, that you have created a record in the Partner database for each project taking part in the TCA') . '</p>';
  }
  else {
    $message = '<p>' . t('Please, before starting a new project input, make sure that:') . '</p>' .
      '<ul><li>' . t('you have created your organisation details ("Project lead organisation")') . '</li>' .
      '<li>' . t('the "Project manager" you want to indicate already has a valid user account on the myTNC website.') . '</li></ul>' .
      '<p>' . t('(You also may indicate your own account as "Project manager" temporarily, and update this later once the permanant project manager has validated his/her user account.)') . '</p>';
  }

  drupal_set_message($message, 'warning');
}

/**
 * Helper to concat the select input in a markup text.
 *
 * @param array $element
 *    The targered select input element.
 *
 * @return string
 *    Return a text in a html format.
 */
function _esf_tc_content_types_field_get_markup_text($element) {
  $return = "";
  if (!empty($element['#title']) && !empty($element['#options'][$element['#default_value'][0]])) {
    $return = "<strong>" . $element['#title'] . ': </strong>' . $element['#options'][$element['#default_value'][0]];
  }
  return $return;
}

/**
 * Helper to compare sensitive data (node with node->original).
 *
 * @param object $node
 *    Target node, node->original must exist.
 *
 * @return bool
 *    Return true if sensitive data have changed.
 */
function _esf_tc_content_types_sensitive_data_changed($node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper_original = entity_metadata_wrapper('node', $node->original);
  $sensitive_fields = _esf_tc_content_types_sensitive_data_fields($node->type);

  $tca_altered = FALSE;

  if (!empty($sensitive_fields) && !empty($node->original)) {
    // Check if changes impact the related TCA status.
    $idx = count($sensitive_fields);

    while ($idx-- && !$tca_altered) {
      $data = $wrapper->$sensitive_fields[$idx]->value();
      $data_old = $wrapper_original->$sensitive_fields[$idx]->value();

      if ($sensitive_fields[$idx] == 'field_project_call_for_projects' && empty($data)) {
        // Workaround for the empty call of project.
        $data = 'empty';
      }
      // If data have changed.
      if (!empty($data) && $data !== $data_old) {
        if (!is_array($data) || empty($data['fid']) || $data['fid'] != $data_old['fid']) {
          $tca_altered = TRUE;
        }
      }
    }
  }

  return $tca_altered;
}

/**
 * Implements hook_node_view_alter().
 */
function esf_tc_content_types_node_view_alter(&$build) {
  if ($build['#entity_type'] == 'node' && $build['#bundle'] == 'esf_tc_whoswho') {
    // Add a link to the Managing Authorities facet.
    $build['links']['node']['#links']['malink'] = array(
      'title' => t('Find Managing Authorities'),
      'href' => 'partners-search',
      'html' => TRUE,
      'attributes' => array(
        'title' => t('Find Managing Authorities'),
      ),
      'query' => array(
        'f' => array('sm_field_org_is_ma_ib:1'),
      ),
    );
  }
}
